# Generated by Django 5.1.7 on 2025-03-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
